### ISSUE TITLE
The exported json file type is data

### ISSUE THREAD

**Issue by kerven88** [wxf4150/esdump#6]
The exported json file type is data，Can be converted to UTF-8 Unicode text format？

![image](https://user-images.githubusercontent.com/51351006/142999072-0c93846b-5200-4e0a-a9f4-6ff466b6e1a4.png)

![image](https://user-images.githubusercontent.com/51351006/142998400-f1ba9cce-927e-4c9b-8fc3-77be973a2caa.png)

**Comment by wxf4150** [comment]
i have change the exported  format to pure text: one document one row.
