### ISSUE TITLE
能否支持指定导出类型

### ISSUE THREAD

**Issue by kerven88** [wxf4150/esdump#8]
类似elasticdump一样，可以指定导出类型type为 alias、template、analyzer、mapping、data，现在默认导出类型应该是data吧？

**Comment by wxf4150** [comment]
目前专注数据“快速”导出。 
alias、mapping、 template、analyzer的导出目前不考虑，这些都可以通过ealstic rest-api,手动完成，具体参考es文档。 
尤其是有中文分词的，更是需要手工配制es-server, 完全没有必要开发这样的的配制功能。
